version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - gocritic
    - revive

run:
  timeout: 5m
  tests: false
  concurrency: 4

issues:
  max-issues-per-linter: 0
  max-same-issues: 0